<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<option value="bear">bear.pyn.ru</option>
<option value="beta">beta.pyn.ru</option>
<option value="crab">crab.pyn.ru</option>
<option value="drozd">drozd.pyn.ru</option>
<option value="fog">fog.pyn.ru</option>
<option value="kappa">kappa.pyn.ru</option>
<option value="leo">leo.pyn.ru</option>
<option value="opossym">opossym.pyn.ru</option>
<option value="panda">panda.pyn.ru</option>
<option value="phoenix">phoenix.pyn.ru</option>
<option value="slowpoke">slowpoke.pyn.ru</option>
<option value="sre">sre.pyn.ru</option>
<option value="suslik">suslik.pyn.ru</option>
<option value="termit">termit.pyn.ru</option>
<option value="titan">titan.pyn.ru</option>
<option value="triton">triton.pyn.ru</option>
<option value="weasel">weasel.pyn.ru</option>
